# Generated by Django 5.1.1 on 2024-09-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='periodicity',
            field=models.CharField(choices=[('every_5_minutes', 'Каждые 5 минут'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'Создано'), ('started', 'Запущено'), ('completed', 'Выполнено')], max_length=50),
        ),
    ]
